# Generated by Django 6.0.3 on 2026-04-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="msg",
            new_name="message",
        ),
    ]
